spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kt_hackathon
    username: hackathon_user
    password: hackathon123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080

logging:
  level:
    com.kt.hackathon: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 